### PR TITLE
EIDR events can have an arbitrary number of geolocations

### PR DESCRIPTION
**Pull request by mawaruDOLL**
Right now, the locations are just urls. They can be added when creating an event or when viewing the event details. They can also be deleted on the details page. The UI doesn't look quite right to me, so any suggestions would be very welcome.

### CODE REVIEW

**Comment by nathanathan** [comment]
Could you make it so users can submit free text locations which are then resolved to geoname links (to be stored internally) using http://www.geonames.org/export/web-services.html

With regard to the UI, I suggest putting the "Add another location field button" below the event fields. Also, I think the locations panel would look better outside of the header in a panel like the one for articles.

**Comment by mawaruDOLL** [comment]
Search is the only web service method I see that will return the name and geonameid. But what if there are multiple search results?  Do we need to use a suggest input so the user can select one of the search results before saving the form?

Also, has a username already been created for EIDR to use when calling the geonames web service or do I need to make a new account?

**Comment by nathanathan** [comment]
There will need to be a way for the user to select the correct location from the search results. Also, displaying a link to the geonames page for each match would help users disambiguate names when there are multiple matches with the same text.

You will need to create the geonames account.

**Comment by mawaruDOLL** [comment]
I'm having a hard time deciding how this location suggest feature will work with the article location suggest feature so I don't really know what form element/plugin to use. It seems to me that they should be separate inputs so the user knows if the location was mentioned in an article or not but that might clutter up the UI.

**Comment by nathanathan** [comment]
I think Toph is about to start working on some mock-ups for this feature. @toph-allen could you chime in here? I think we'll want a modal dialog to appear when an article is added that has all the suggestions from it.

**Comment by mawaruDOLL** [comment]
The work on implementing geolocations was finished in another branch (see #318), so I'm closing this pull request.

**Comment by toph-allen** [comment]
I'm going to be working on mock-ups and stuff broadly this weekend, and when I'm doing that, I'll look through this thread and the repo's existing issues, and incorporate them into my thinking, and comment where there seems to be need for clarification. Is that okay?

**Pull request closed without merging**
