### PR TITLE
Limit EIDR event creation to admin users

### PR DESCRIPTION
**Pull request by mawaruDOLL**
Only admins can create and update events. Buttons associated with these tasks have been hidden for all other users.

### CODE REVIEW

**Comment by nathanathan** [comment]
I am going to hold off on merging this until we have a way to create admin users.

**Comment by nathanathan** [comment]
@mawaruDOLL Could you resolve the conflicts in this?

**Comment by mawaruDOLL** [comment]
The conflicts are resolved now.

**Comment by sturmer-eha** [comment]
👍

**Pull request merged**
