### PR TITLE
Add EIDR event creation page

### PR DESCRIPTION
**Pull request by mawaruDOLL**
The story says only authorized users can add events. I wasn't sure if this meant only admins or not, so any registered user can add events. I included a new link in the menu to get to the event form but I expect this will be removed/reworded in the future as the user defined events are fully implemented. There is also a count of the currently existing user events on the event form but it's just for testing to prove the events are being saved since they can't actually be viewed yet.

Is there any kind of validation that should be performed on the event name other than making sure it isn't blank?

### CODE REVIEW

**Comment by nathanathan** [comment]
Could you change the formatting to 2 space soft tabs for consistency with the rest of our code?

**Comment by nathanathan** [comment]
Other validation on the event name isn't necessary.

**Comment by mawaruDOLL** [comment]
I changed the tabs to spaces.

**Comment by nathanathan** [comment]
👍 Looks good

**Pull request merged**
